version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/DGIT_V2_Client/build/

permissions:
  - object: /
    mode: 755
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root