name: DGIT-V2 Deployment

on:
  push:
    branches: [ main ]

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Use Node.js version 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Build
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
          yarn build

    - name: Create Zip File
        run: zip out.zip -r ./out/*
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync ./${{ secrets.BUILD_DIRECTORY }} ${{ secrets.AWS_S3_BUCKET_NAME }} --acl public-read --delete

      - name: CodeDeploy
        run: aws deploy create-deployment --application-name DGIT-V2 --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name DGIT-V2-Group bucket=dgit-v2,bundleType=zip,key=out.zip