name: PullRequest To Main Branch

on:
  pull_request:
    branches: [ main ]

jobs:
  JEST-TESTING:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Use Node.js version 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      - name: Install Package
        run: yarn

      - name: Jest Test
        run: yarn test
  JSET-COVERAGE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: artiomtr/jest-coverage-report-action@v1.3
        with:
          github-token: ${{ secrets.DGIT_TOKEN }}

